
- hosts: reporters

  pre_tasks:
    
    - name: make sure java8 is installed
      win_chocolatey: name=jdk8
      when: ansible_os_family == "Windows"

  roles:
    - role: reporter
      db_connection_string: jdbc://postgres:5432/reporter
      db_username: postgres
      db_password: mysupersecurepassword
