
# validation

- name: assert all vars are set
  assert: { that: "{{ item }} != '' " }
  with_items:
  - app_name
  - clear_temp_folder
  - service_name
  - main_class
  - installation_folder
  - clear_before_install
  - server_port
  - jmx_port
  - service_plist_file_path
  - installer_file_name
  - ansible_user_id
  - s3_download_url
  - launcher_file_name
  - db_connection_string
  - db_username

# required dependencies

- name: make sure java is installed on the machine
  command: java -version
  register: java_test
  ignore_errors: yes

- name: fail if java is not found
  fail:
    msg: java must be accesible in path
  when: java_test.rc != 0

# set temp folder

- name: make sure temp folder
  file:
    path: "{{ temp_folder }}"
    state: directory
    owner: "{{ ansible_user_id }}"
  become: yes

# download the file

- name: download zip from s3 url
  get_url:
    url: "{{ s3_download_url }}"
    dest: "{{ temp_folder }}/{{ installer_file_name }}"
  when: custom_download_url == ""

- name: download zip from custom url
  get_url:
    url: "{{ custom_download_url }}"
    dest: "{{ temp_folder }}/{{ installer_file_name }}"
  when: custom_download_url != ""

# stop old service

- name: stop the old service
  command: "launchctl unload {{ service_plist_file_path }}"
  become: yes

# delete old installation (optional)

- name: clear old installation folder
  file: 
    path: "{{ installation_folder }}"
    state: absent
  when: clear_before_install == True

# unpack and copy all the files to the installation folder

- name: make sure installation folder exists
  file:
    path: "{{ installation_folder }}"
    state: directory
    owner: "{{ ansible_user_id }}"
  become: yes

- name: unzip the file
  unarchive:
    src: "{{ temp_folder }}/{{ installer_file_name }}"
    dest: "{{ installation_folder }}"
    remote_src: yes
    owner: "{{ ansible_user_id }}"
  become: yes

- name: copy plist
  template:
    src: service.plist.j2
    dest: "{{ service_plist_file_path }}"
    # in mac - plist owner is root
    owner: root
  become: yes

# REMOVEME fix when zip will not contain fat jar 
- name: find fat jar file in folder
  find:
    paths: "{{ installation_folder }}/libs"
    patterns: 'manager-*.jar'
  register: find_fat_jar

- name: save fatjar path
  set_fact:
    fat_jar_file_name: "{{ find_fat_jar.files[0].path }}"

- name: copy start script
  template:
    src: start.sh.j2
    dest: "{{ installation_folder }}/{{ launcher_file_name }}"
    mode: 0755
    owner: "{{ ansible_user_id }}"
  become: yes

# configure installed 

- name: update application properties file
  lineinfile:
    path: "{{ installation_folder }}/config/application.properties"
    line: "{{ item.key }}={{ item.value }}"
    regexp: "{{ item.regexp }}"
  with_items:
    
    - key: server.port
      value: "{{ server_port }}"
      regexp: '^server\.port='
    
    - key: spring.datasource.url
      value: "{{ db_connection_string }}"
      regexp: '^spring\.datasource\.url='
    
    - key: spring.datasource.username
      value: "{{ db_username }}"
      regexp: '^spring\.datasource\.username='
    
    - key: spring.datasource.password
      value: "{{ db_password }}"
      regexp: '^spring\.datasource\.password='
    
  become: yes

- name: set permissions for logs folder
  file:
    path: "{{ installation_folder }}/logs"
    state: directory
    mode: 0777
    owner: "{{ ansible_user_id }}"
  become: yes

- name: reset pairing key
  file:
    path: "{{ installation_folder }}/config/pairing.conf.xml"
    state: absent
  become: yes

# start the service (optional)

- name: load the service
  command: "launchctl load {{ service_plist_file_path }}"
  become: yes
  when: start_after_install is defined and start_after_install == True

# clear temp files (optional)

- name: clear temp folder
  file:
    path: "{{ temp_folder }}"
    state: absent
  become: yes
  when: clear_temp_folder == True

# expose role output

- name: expose role output
  set_fact:
    "{{ role_name }}":
      server_port: "{{ server_port }}"
      jmx_port: "{{ jmx_port }}"
      installation_folder: "{{ installation_folder }}"
      configuration_file: "{{ installation_folder }}\\config\\application.properties"
